name: Bazel Build

on: [pull_request]

jobs:
  macos-test:
    name: macOS test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Swift environment
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.1'
      - name: test
        run: bazelisk build //...
